### ISSUE TITLE
Visual bug? - link between two nodes doesn't get erased after pressing backspace/delete

### ISSUE THREAD

**Issue by mykongee** [kousun12/eternal#19]
Hello 👋 really neat project! I really appreciate the fact that you can make a really complex audiovisual project with a simple, descriptive UI. As I was playing around with it, I noticed an interaction with the UI and was wondering if it was intentional?

**Description**
When I press `backspace` to disconnect two nodes, the changes in audio reflect immediately, whereas the UI seems to not update.
However, at the same time when pressing `backspace` the UI seems to be outdated as I would expect that the link would be erased to keep the UI in sync with the audio playback.

**To reproduce**
Click on a link between two nodes.
![image](https://user-images.githubusercontent.com/10676303/201050341-9da2dbd2-a721-45f3-baa8-2e9cbc3e5aa1.png)

After pressing 'backspace', the UI appears like this: 
![image](https://user-images.githubusercontent.com/10676303/201050873-49588b74-3802-4872-abb1-a700c7204d3e.png)

As a user, I would expect that the link wouldn't be there in the UI anymore. 
Although I did notice that upon moving the canvas or zooming in, the UI seems to have been updated and the link is gone.

**Comment by kousun12** [comment]
Hi, thanks for the report. I haven't looked at this project in a couple of years, but just brought it back and I've fixed this issue. Cheers.
