### ISSUE TITLE
Update dependencies to current environment

### ISSUE THREAD

**Issue by version-aotearoa** [kousun12/eternal#6]
Any chance you could update this project to run with current node -v v17.0.1 etc...?
I'd love to use this interface to build some creative projects.

**Comment by kousun12** [comment]
Hi - yeah I can probably get to it some time this week. Stay tuned...

**Comment by version-aotearoa** [comment]
🙏

**Comment by kousun12** [comment]
got around to bringing this project back up to speed with most dependencies today
